# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'filterDesign.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import pyqtgraph as pg
from PyQt5 import QtCore, QtGui, QtWidgets
from pyqtgraph import PlotWidget

import UI_Layout.icons as icons
from filterDesignBackendSpare2 import Backend


class Ui_FilterDesigner(object):
    def setupUi(self, FilterDesigner):
        FilterDesigner.setObjectName("FilterDesigner")
        FilterDesigner.resize(1280, 744)
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap(":/appIcon/processing.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        FilterDesigner.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(FilterDesigner)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.applicationGraphs = QtWidgets.QGroupBox(self.frame_2)
        self.applicationGraphs.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        self.applicationGraphs.setFont(font)
        self.applicationGraphs.setAlignment(QtCore.Qt.AlignCenter)
        self.applicationGraphs.setObjectName("applicationGraphs")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.applicationGraphs)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.filteredSignal = PlotWidget(self.applicationGraphs)
        self.filteredSignal.setMinimumSize(QtCore.QSize(0, 0))
        self.filteredSignal.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.filteredSignal.setObjectName("filteredSignal")
        self.originalApplicationSignal = PlotWidget(self.applicationGraphs)
        self.originalApplicationSignal.setMinimumSize(QtCore.QSize(0, 0))
        self.originalApplicationSignal.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.originalApplicationSignal.setObjectName("originalApplicationSignal")
        self.verticalLayout_7.addWidget(self.originalApplicationSignal)
        self.verticalLayout_7.addWidget(self.filteredSignal)
        self.verticalLayout_8.addWidget(self.applicationGraphs)
        self.mousePadGroupBox = QtWidgets.QGroupBox(self.frame_2)
        self.mousePadGroupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.mousePadGroupBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        self.mousePadGroupBox.setFont(font)
        self.mousePadGroupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.mousePadGroupBox.setObjectName("mousePadGroupBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.mousePadGroupBox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label = QtWidgets.QLabel(self.mousePadGroupBox)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.mousePad = PlotWidget(self.mousePadGroupBox)
        self.mousePad.setMinimumSize(QtCore.QSize(0, 0))
        self.mousePad.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.mousePad.setObjectName("mousePad")
        self.verticalLayout_5.addWidget(self.mousePad)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_6.addItem(spacerItem)
        self.generateSignal = QtWidgets.QPushButton(self.mousePadGroupBox)
        self.generateSignal.setObjectName("generateSignal")
        self.horizontalLayout_6.addWidget(self.generateSignal)
        spacerItem1 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_6.addItem(spacerItem1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.verticalLayout_8.addWidget(self.mousePadGroupBox)
        self.gridLayout.addWidget(self.frame_2, 0, 1, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMaximumSize(QtCore.QSize(700, 16777215))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.filterDesignGroupBox = QtWidgets.QGroupBox(self.frame)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        self.filterDesignGroupBox.setFont(font)
        self.filterDesignGroupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.filterDesignGroupBox.setObjectName("filterDesignGroupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.filterDesignGroupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.unitCirclePlot = PlotWidget(self.filterDesignGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.unitCirclePlot.sizePolicy().hasHeightForWidth()
        )
        self.unitCirclePlot.setSizePolicy(sizePolicy)
        self.unitCirclePlot.setMinimumSize(QtCore.QSize(200, 200))
        self.unitCirclePlot.setMaximumSize(QtCore.QSize(200, 200))
        self.unitCirclePlot.setObjectName("unitCirclePlot")

        # Create a CircleROI
        circle_roi = pg.CircleROI(
            [-1, -1],
            size=(2, 2),
            pen=pg.mkPen(color="orange", width=2),
            movable=False,
            resizable=False,
            rotatable=False,
        )
        # Create lines for the X and Y axes
        x_axis = pg.InfiniteLine(
            angle=0, movable=False, pen=pg.mkPen(color="w", width=1)
        )
        y_axis = pg.InfiniteLine(
            angle=90, movable=False, pen=pg.mkPen(color="w", width=1)
        )

        # Add the CircleROI and axes to the PlotWidget
        self.unitCirclePlot.addItem(circle_roi)
        self.unitCirclePlot.addItem(x_axis)
        self.unitCirclePlot.addItem(y_axis)
        self.unitCirclePlot.hideAxis("bottom")
        self.unitCirclePlot.hideAxis("left")

        circle_roi.removeHandle(0)
        # Set the view range
        self.unitCirclePlot.setMouseEnabled(x=False, y=False)
        self.unitCirclePlot.setRange(xRange=(-1, 1), yRange=(-1, 1))
        self.unitCirclePlot.setLimits(xMin=-1.1, xMax=1.1, yMin=-1.1, yMax=1.1)

        self.horizontalLayout_2.addWidget(self.unitCirclePlot)

        self.zPlaneDesignControls = QtWidgets.QGroupBox(self.filterDesignGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.zPlaneDesignControls.sizePolicy().hasHeightForWidth()
        )
        self.zPlaneDesignControls.setSizePolicy(sizePolicy)
        self.zPlaneDesignControls.setMinimumSize(QtCore.QSize(131, 191))
        self.zPlaneDesignControls.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.zPlaneDesignControls.setFont(font)
        self.zPlaneDesignControls.setAlignment(QtCore.Qt.AlignCenter)
        self.zPlaneDesignControls.setObjectName("zPlaneDesignControls")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.zPlaneDesignControls)
        self.verticalLayout.setObjectName("verticalLayout")
        self.addPole = QtWidgets.QPushButton(self.zPlaneDesignControls)
        self.addPole.setObjectName("addPole")
        self.verticalLayout.addWidget(self.addPole)
        self.addZero = QtWidgets.QPushButton(self.zPlaneDesignControls)
        self.addZero.setObjectName("addZero")
        self.verticalLayout.addWidget(self.addZero)
        self.removeAllPoles = QtWidgets.QPushButton(self.zPlaneDesignControls)
        self.removeAllPoles.setObjectName("removeAllPoles")
        self.verticalLayout.addWidget(self.removeAllPoles)
        self.removeAllZeros = QtWidgets.QPushButton(self.zPlaneDesignControls)
        self.removeAllZeros.setObjectName("removeAllZeros")
        self.verticalLayout.addWidget(self.removeAllZeros)
        self.resetDesign = QtWidgets.QPushButton(self.zPlaneDesignControls)
        self.resetDesign.setObjectName("resetDesign")
        self.verticalLayout.addWidget(self.resetDesign)
        self.addConjugatesCheckBox = QtWidgets.QCheckBox(self.zPlaneDesignControls)
        self.addConjugatesCheckBox.setObjectName("addConjugatesCheckBox")
        self.verticalLayout.addWidget(self.addConjugatesCheckBox)
        self.applyFilterButton = QtWidgets.QPushButton(self.zPlaneDesignControls)
        self.applyFilterButton.setObjectName("applyFilterButton")
        self.verticalLayout.addWidget(self.applyFilterButton)
        self.horizontalLayout_2.addWidget(self.zPlaneDesignControls)
        self.verticalLayout_6.addWidget(self.filterDesignGroupBox)
        self.allPassDesignGroupBox = QtWidgets.QGroupBox(self.frame)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        self.allPassDesignGroupBox.setFont(font)
        self.allPassDesignGroupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.allPassDesignGroupBox.setObjectName("allPassDesignGroupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.allPassDesignGroupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pickFilterWidget = QtWidgets.QWidget(self.allPassDesignGroupBox)
        self.pickFilterWidget.setMaximumSize(QtCore.QSize(16777215, 50))
        self.pickFilterWidget.setObjectName("pickFilterWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.pickFilterWidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pickFilterLabel_2 = QtWidgets.QLabel(self.pickFilterWidget)
        self.pickFilterLabel_2.setMinimumSize(QtCore.QSize(80, 0))
        self.pickFilterLabel_2.setMaximumSize(QtCore.QSize(80, 60))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pickFilterLabel_2.setFont(font)
        self.pickFilterLabel_2.setObjectName("pickFilterLabel_2")
        self.horizontalLayout_4.addWidget(self.pickFilterLabel_2)
        self.allPassLibrary = QtWidgets.QComboBox(self.pickFilterWidget)
        self.allPassLibrary.setObjectName("allPassLibrary")
        self.horizontalLayout_4.addWidget(self.allPassLibrary)
        self.verticalLayout_2.addWidget(self.pickFilterWidget)
        self.InputAWidget = QtWidgets.QWidget(self.allPassDesignGroupBox)
        self.InputAWidget.setMaximumSize(QtCore.QSize(16777215, 50))
        self.InputAWidget.setObjectName("InputAWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.InputAWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.inputALabel = QtWidgets.QLabel(self.InputAWidget)
        self.inputALabel.setMinimumSize(QtCore.QSize(80, 0))
        self.inputALabel.setMaximumSize(QtCore.QSize(80, 60))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.inputALabel.setFont(font)
        self.inputALabel.setObjectName("inputALabel")
        self.horizontalLayout.addWidget(self.inputALabel)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.InputAWidget)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.horizontalLayout.addWidget(self.doubleSpinBox)
        self.verticalLayout_2.addWidget(self.InputAWidget)
        self.applyFilterButton_2 = QtWidgets.QPushButton(self.allPassDesignGroupBox)
        self.applyFilterButton_2.setObjectName("applyFilterButton_2")
        self.verticalLayout_2.addWidget(self.applyFilterButton_2)
        self.verticalLayout_6.addWidget(self.allPassDesignGroupBox)
        self.frequencyResponseGroupBox = QtWidgets.QGroupBox(self.frame)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        self.frequencyResponseGroupBox.setFont(font)
        self.frequencyResponseGroupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.frequencyResponseGroupBox.setObjectName("frequencyResponseGroupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frequencyResponseGroupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.magFrequencyResponse = PlotWidget(self.frequencyResponseGroupBox)
        self.magFrequencyResponse.setMinimumSize(QtCore.QSize(0, 0))
        self.magFrequencyResponse.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.magFrequencyResponse.setObjectName("magFrequencyResponse")
        self.magFrequencyResponse.setTitle("Filter Magnitude Response")
        self.magFrequencyResponse.setLabel("bottom", "Frequency (rad/sample)")
        self.magFrequencyResponse.setLabel("left", "Phase (radians)")
        self.verticalLayout_3.addWidget(self.magFrequencyResponse)
        self.phaseFrequencyResponse = PlotWidget(self.frequencyResponseGroupBox)
        self.phaseFrequencyResponse.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.phaseFrequencyResponse.setObjectName("phaseFrequencyResponse")
        self.phaseFrequencyResponse.setTitle("Filter Phase Response")
        self.phaseFrequencyResponse.setLabel("bottom", "Frequency (rad/sample)")
        self.phaseFrequencyResponse.setLabel("left", "Phase (radians)")
        self.verticalLayout_3.addWidget(self.phaseFrequencyResponse)
        self.verticalLayout_6.addWidget(self.frequencyResponseGroupBox)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        FilterDesigner.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(FilterDesigner)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        FilterDesigner.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(FilterDesigner)
        self.statusbar.setObjectName("statusbar")
        FilterDesigner.setStatusBar(self.statusbar)
        self.actionImport_Signal = QtWidgets.QAction(FilterDesigner)
        self.actionImport_Signal.setObjectName("actionImport_Signal")
        self.menuFile.addAction(self.actionImport_Signal)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(FilterDesigner)
        QtCore.QMetaObject.connectSlotsByName(FilterDesigner)

    def retranslateUi(self, FilterDesigner):
        _translate = QtCore.QCoreApplication.translate
        FilterDesigner.setWindowTitle(_translate("FilterDesigner", "Filter Designer"))
        self.applicationGraphs.setTitle(
            _translate("FilterDesigner", "Application Signals")
        )
        self.mousePadGroupBox.setTitle(_translate("FilterDesigner", "Mouse Pad"))
        self.label.setText(
            _translate("FilterDesigner", "Generate signal by moving your mouse")
        )
        self.generateSignal.setText(_translate("FilterDesigner", "Generate Signal"))
        self.filterDesignGroupBox.setTitle(
            _translate("FilterDesigner", "Filter Design")
        )
        self.zPlaneDesignControls.setTitle(
            _translate("FilterDesigner", "Design Controls")
        )
        self.addPole.setText(_translate("FilterDesigner", "Add Pole"))
        self.addZero.setText(_translate("FilterDesigner", "Add Zero"))
        self.removeAllPoles.setText(_translate("FilterDesigner", "Remove all Poles"))
        self.removeAllZeros.setText(_translate("FilterDesigner", "Remove all Zeroes"))
        self.resetDesign.setText(_translate("FilterDesigner", "Reset Design"))
        self.addConjugatesCheckBox.setText(
            _translate("FilterDesigner", "Add Conjugates")
        )
        self.applyFilterButton.setText(_translate("FilterDesigner", "Apply Filter"))
        self.allPassDesignGroupBox.setTitle(
            _translate("FilterDesigner", "All-Pass FilterDesign")
        )
        self.pickFilterLabel_2.setText(_translate("FilterDesigner", "Pick Filter"))
        self.inputALabel.setText(_translate("FilterDesigner", "Inpupt 'a'"))
        self.applyFilterButton_2.setText(
            _translate("FilterDesigner", "Apply All-Pass Filter")
        )
        self.frequencyResponseGroupBox.setTitle(
            _translate("FilterDesigner", "Frequency Response")
        )
        self.menuFile.setTitle(_translate("FilterDesigner", "File"))
        self.menuHelp.setTitle(_translate("FilterDesigner", "Help"))
        self.actionImport_Signal.setText(_translate("FilterDesigner", "Import Signal"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    with open("UI_Layout/stylesheet.qss", "r") as f:
        stylesheet = f.read()
        app.setStyleSheet(stylesheet)
    FilterDesigner = QtWidgets.QMainWindow()
    ui = Ui_FilterDesigner()
    ui.setupUi(FilterDesigner)
    backend = Backend(ui)
    FilterDesigner.show()
    sys.exit(app.exec_())
